services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    ports:
      - $PROXY_PORT:8388
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=$SHADOWSOCKS_PASSWORD
    restart: always
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  telemt:
    image: ghcr.io/telemt/telemt:latest
    build: .
    container_name: telemt
    restart: unless-stopped
    ports:
      - "$MTPROTO_PORT:25443"
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9091:9091"
    working_dir: /run/telemt
    volumes:
      - ./telemt/config.toml:/run/telemt/config.toml:ro
    tmpfs:
      - /run/telemt:rw,mode=1777,size=1m
    environment:
      - RUST_LOG=info
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536