services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    ports:
      - $PROXY_PORT:8388
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=$SHADOWSOCKS_PASSWORD
    restart: always
  socks5:
    image: serjs/go-socks5-proxy
    container_name: socks5
    restart: unless-stopped
    ports:
      - $SOCKSPROXY_PORT:1080
    environment:
      - PROXY_USER=$SOCKSPROXY_USERNAME
      - PROXY_PASSWORD=$SOCKSPROXY_PASSWORD
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'